### ISSUE TITLE
Quickicon changes break b/c

### ISSUE THREAD

**Issue by brianteeman** [joomla/backend-template#231] opened 2019-05-25 14:23 UTC
I reported this before here https://github.com/joomla/backend-template/pull/196#issuecomment-491507215 but it was completely ignored and the breaking change was merged anyway so I will re-open it and repeat that the changes to quickicons (**which should NOT have been part of the template repo**) has completely broken the ability for 3pd to add their own icon to the quickicon set. Just because we can break b/c doesn't mean that we should not care about it at all. There **must** be a really good reason to do so - I haven't seen any evidence of that (_it might exist but no one answered my first post_)

To be clear currently in Joomla 3 AND Joomla 4 an extension can place an icon in the quickicons. This is an example of akeeba backup from @nikosdion placing an icon in the quickion module

![image](https://user-images.githubusercontent.com/1296369/58370593-42442300-7f00-11e9-974e-b5db93dd6735.png)

This is the current dashboard from this repo also with akeeba backup installed

![image](https://user-images.githubusercontent.com/1296369/58370605-6869c300-7f00-11e9-91ab-376f08376502.png)

Exactly as I stated in https://github.com/joomla/backend-template/pull/196#issuecomment-491507215 and was ignored - the template making changes to the quickicon module (which it should never have done) has **broken** the behaviour.

All these non-template changes should have been made in the main repo where they could have been properly reviewed and tested and would not have just been either directly committed or merged without review. You cannot say that this was correctly reviewed as I clearly pointed out before the merge that this was a bad change.

### The people working in this repo are making it very hard for anyone to have any faith in the quality of the work that is taking place here or that it can ever be submitted as a pull request.

**Comment by brianteeman** [comment] 2019-05-25 14:25
Yes this is a rant. It is a rant because you have been given a huge responsibility and appear to be completely ignoring legitimate concerns and not sticking to your own promises. Everyone who contributes to Joomla and everyone whose livelihood depends on the success of Joomla 4 has the right to express their concerns.

**Comment by nikosdion** [comment] 2019-05-25 16:51
QuickIcons were added in Joomla 1.7.0 as plugins by yours truly because before that it was a Wild West of developers trying to work around template CSS and injecting arbitrary HTML in what was hopefully the right place. This made the Joomla control panel page a finicky and useless area – which happened to be the first thing users saw.

True, you could use modules but not all functionality is conducive to being a module. Seeing backup status, quickly clearing the cache or showing update status are prime examples. People want all of that at a glance information in a SINGLE place of their control panel, not scattered around. 

Therefore I agree with Brian that this breaking change is a regression, one that takes Joomla back more than a decade. I would understand if there was a reason other than we did it because we could. Shame.

**Comment by rdeutz** [comment] 2019-05-25 17:09
This b/c break was not intended so thanks for reporting it again, the bug will be fixed.

**Comment by bembelimen** [comment] 2019-06-05 23:17
Thx https://github.com/joomla/backend-template/pull/279

**Closed as completed by bembelimen** 2019-06-05 23:17 UTC

**Comment by nikosdion** [comment] 2019-10-29 13:09
I know this is a dead issue but two weeks ago I had to dive deep to figure out why my quick icon plugin was being rendered wrong in the latest J4 alpha build. Since I was moving I was left without Internet except for a 4G connection so here I am dealign with the backlog :)

The current quickicons implementation in Joomla 4 is backwards incompatible with Joomla 3 for no reason at all. It removes existing functionality and **also** ends up misplacing quick icons. I believe I am the right person to comment on that since I was the one implementing the quick icons feature in 1.7.0 and know how and why I implemented it (not to mention that this information had also been present in code comments).

The `onGetIcons` event has a single parameter, `$context`. This allows _third party extensions_ to define their own quick icon areas powered by modules. The vision behind that was third party components where add-on functionality is implemented by plugins which can also render relevant icons in the component's control panel.

Conversely, the grouping of control panel icons in the component or module rendering them was determined by the `group` key of the array returned by the quick icon plugin. This allowed plugins, for example, to provide a user-facing control defined in the manifest XML, letting users choose where to place the icon. That's how Akeeba Backup was implementing its quick icon plugin up to and including version 6.6.0.

Note that in Joomla 1.7, 2.5 and 3.x the administrator quick icon module was passing the context `mod_quickicon` which made perfect sense: this is the context in which the icons are displayed and the returned `group` determined in which group within the module to display them.

In Joomla 4 you botched this up. Now the context defines the grouping and the returned `group` is ignored! Worse than that, you now have a "3rd party" quick icons module which sends the context value "mod_quickicon" and bins all quick icons together, with no rhyme or reason. It makes the whole implementation of quick icons counter-intuitive and confusing to the user.

Since the new context and the old group use incompatible values any plugin allowing the user to select where to display the icon has to remove that functionality. The reason is that for at least 2 years after Joomla 4 is released us developers need to support both J3 and J4 per Joomla's (rather disastrous, but that's an entirely different issue) planning. Since plugin options are rendered by a static XML and there's no way to filter them by Joomla version (at least not without having to use a different, content plugin!!!) we can neither provide values that make sense for both Joomla version nor display two different options for the same things depending on the Joomla version (that's a UX anti-pattern). Therefore we have to take away control from the users.

Furthermore, by abusing the context as grouping information you are essentially forcing us to hardcode the grouping in our code since quick icon plugins respond based on the context. 

On top of that, any plugin responding to mod_quickicon context will be placed in the junk bin of "3rd party", below the fold on most devices, making our information invisible and missing the point of having quick icons.

Finally, the default and hard to change grouping is haphazard to say the least. Privacy requests and language overrides are mashed into the Update Checks module. In which distorted universe is a user deletion request an update request?! In the end of the day we're creating a UI which teaches users to ignore information on their screen.

The "solution" to this issue is worse than the original issue. A unnecessary backwards incompatible change was introduced just because someone could (or, should I say, just because someone _couldn't apply common sense_). You could have addressed this issue by having each quick icon module filter the returned icon definitions by group while passing the same context, mod_quickicons. If you were worried about icon plugins running multiple times you could have created a stupid simple helper with a static icon cache that only persists throughout the page load. You know, PHP has static properties for this reason. If it's empty (first module instance), load it up. Next quickicons module reuses the icon cache instead of hitting the plugins. No need to break b/c and force developers to hardcode grouping in their plugins.

**Comment by brianteeman** [comment] 2019-10-29 13:57
@nikosdion the only way you will get anyone to hear this is to post it in the main repo. Clearly the only people reading it here (except for me) thought the changes were a good idea and ignored our comments. Maybe posting on the main repo will get real peoples attention

**Comment by nikosdion** [comment] 2019-10-29 16:25
So, here is my dilemma. Post in the main repo, be told that there's another repo (that nobody links to) where development takes place. Find and write to that repo, nobody cares to give feedback. 

All I can do is explain why the b/c change is utterly misguided (to put it mildly) and do so in the repo where the developers that made the change use and in public because _scripta manent_. 

If the repo coordinators want me to fix what they broke, sure, I can gladly do so. It will take me about 30' to refactor the mess (no JS or CSS needs to be touched, thank Cthulhu) and 30 days to talk about it in circles. I reckon there's even a 70% chance my PR would be accepted! I can afford that time and chance. If they don't ask me to help them fix it or they don't produce a fix based on the mostly concrete ideas I've given them it's not on me.

**Comment by brianteeman** [comment] 2019-10-29 16:33
This repo is dead and it looks like x0% of the people who contributed to the code here have gone as well
