### ISSUE TITLE
Newbie Here, just need to install a working version to see the new admin template ?

### ISSUE THREAD

**Issue by Chacapamac** [joomla/backend-template#277] opened 2019-06-02 16:31 UTC
### System information (as much as possible)
Mamp on Mac

### Additional comments
I try to download the Joomla version here and install but its asking for some Local environment setup.

What I want its to simply being able to see the new admin template.

My mamp environment is for my work and I’m a bit worry to modify it...

Any help/infos will be welcome !

**Comment by drmenzelit** [comment] 2019-06-02 17:36
You should have a look in the docs: 
https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment

**Comment by Chacapamac** [comment] 2019-06-03 13:18
Yes, I look there, seem to be quite complicated and I’m a bit afraid to play with my work MAMP environment.
No other ways to simply see what the admin template look like. Maybe having some screenshot ?. 

This is not to participate in the coding (I’m not a coder) but view the last, newer UI/UX design.

**Comment by pe7er** [comment] 2019-06-03 13:39
Actually, if a picture (screenshot) says more than a thousand words,
then a real dynamic Joomla 4 test site where you can click all the links and see all UX in action, 
will say more than a million words :-)

You can run the Joomla 4 + admin template on your MAMP just as any other Joomla website.
You can run composer + npm for this project only if you run it from within the Joomla 4 test site and don't use the global option ("-g").

**Comment by Chacapamac** [comment] 2019-06-04 12:50
Thanks for the infos Peter, I’m getting to it.
If I understand well, I can install the Joomla in my MAMP without screwing up my work environment.

I’m a little lost on what exactly I’m trying to achieve here and the overall process, I will.

**Comment by Hackwar** [comment] 2019-06-05 09:31
To make this quick:
- Download the release branch of this repository
- Unzip in the folder where you want to install it
- Run ```composer install``` in that folder
- Run ```npm i``` in that folder
- Open the URL to the folder in a browser and run through installation.

Since this is not a bug report, I'm closing this one.

**Closed as completed by Hackwar** 2019-06-05 09:31 UTC

**Comment by Chacapamac** [comment] 2019-06-05 12:07
Do I need to create a database before install, I Guess yes?

**Comment by drmenzelit** [comment] 2019-06-05 12:34
The system will create the database automatically during the installation, if your Mysql user has the appropriate rights

**Comment by simbus82** [comment] 2019-06-25 14:03
And... how to build an installable ".zip" like "nightly" Joomla 4 packages?
There is no documentation...

**Comment by chmst** [comment] 2019-06-25 17:39
As soon as you have done all the steps mentioned above (composer install, npm i) you can addinto a zip file the directories and files which are in the nightly build.

**Comment by bembelimen** [comment] 2019-06-25 17:56
You can create your ZIP via https://github.com/joomla/backend-template/blob/release/build/build.php
